### ISSUE TITLE
#48in24: armstrong-numbers 2024-11-26

### ISSUE THREAD

**Issue by mk-mxp** [exercism/php#825]
- [x] Run `bin/configlet sync -u -e armstrong-numbers --yes --docs --filepaths --metadata --tests include` (updates the Markdown files and maybe `tests.toml`)
  - docs: instructions unsynced: armstrong-numbers
  - metadata: unsynced: armstrong-numbers
- [x] Drop strict types comments from test file and example code (these are useless)
- [x] Add and sync test meta data to tests (`uuid` / `@testdox` in DocBlocks)
- [x] Decide on adding / adjusting / ordering test cases to match current problem specs
  - armstrong-numbers: missing 2 test cases

Do not redesign the student's interface or add test cases that would invalidate existing community solutions. These are extra tasks, which should be discussed in advance.

**Comment by tomasnorre** [comment]
I have implemented the two missing test cases, but the first of them https://github.com/exercism/problem-specifications/blob/main/exercises/armstrong-numbers/canonical-data.json#L86 is failing. I don't know to be honest if it's due to the to the 107 bit as stated in comment. 

I had to force the last two to `(int)`, otherwise PHP thinks they are float due to length.

**Comment by mk-mxp** [comment]
I'd mark both tests as ignored. Casting to `(int)` doesn't solve the problem. In `tests.toml`:

```
include = false
comment = "PHP does not support integers > 64bit in its standard library"
```

I think it would be totally overkill to ask students to use BCMath or GMP extension functions for arbitrary integer sizes.
